config/routes.rb
Cfa::Application.routes.draw do

  resources :uploaders do
    match '/uploaders' => 'uploaders#index'

  end

  resources :gradings  do
    collection do
      post '/answers'
      get '/add_grade_system'
      get '/add_point_grading_detail'
      get '/add_point_grading'
    end
  end

  resources :rooms

  resources :school_grades
  resources :assignment_libraries  do
    collection do
      get 'question_search'
      get 'destroy_question'
      get 'add_question'
    end
  end
  resources :school_classes do
    collection do
      get 'student_search'
      put 'add_student'
      put 'remove_student'
    end
  end

  resources :hall_of_fames
  
  resources :sponsors  do

  end
  resources :comments
  resources :relationship_types

  resources :questions

  resources :institutions do
    collection do
      post  'delete_institution'
      get 'city_autocomplete'
    end
  end


  resources :menu_items

  resources :game_assets

  resources :grade_systems

  resources :hobbies

  resources :elements

  resources :concepts

  resources :subjects

  resources :healths

  resources :residences

  resources :assignments do
    collection do
      get 'student_search'
    end
  end

  match '/educations/change_emergency_contacts'  => "educations#change_emergency_contacts"
  match '/users/change_healths' => "users#change_healths"
  resources :educations

  resources :eductations

  resources :races

  resources :phonetypes

  resources :phones

  resources :emails

  resources :states

  resources :cities

  resources :addresses

  resources :links

  resources :badges



  resources :contents do
    collection do
      match '/load_images/:id' => "contents#load_images"
      get  "search_content"
      match '/tags'  => "contents#tag"
      get 'load_tags'
      match '/edit_tag_name' => 'contents#edit_tag_name'
      match '/remove_tag/:tag_id' => 'contents#remove_tag'

    end

  end
  resources :content_photos do
    collection do
      post 'make_default'
      post 'search/:file_name' => "content_photos#search"
      post 'load_image' => "content_photos#load_image"
    end
  end
  resources :pictures
  resources :galleries do
    resources :pictures do
      collection do
        post 'make_default'
      end
    end
  end

  authenticated :user do
    root :to => 'home#index'
  end
  root :to => "home#index"
  devise_for :users,:controllers => { :registrations => "registrations",:sessions => "sessions",:passwords => "passwords",:invitations => "invitations" }

  devise_scope :user do
    match 'users/create_parent' => 'invitations#create_parent'
    match '/advanced_invitation' => 'users#advanced_invitation'

  end
  resources :users do
    resources :additional_emergency_contacts
    collection do
      post 'create_advanced_invitation'
    end

  end

  get  '/chatroom' => 'chats#room', :as => :chat
  get '/home/city_autocomplete'
  post '/new_message' => 'chats#new_message', :as => :new_message
  match '/user/update' => "users#update_user"
  match 'users/add_emergency_contact' => 'users#add_emergency_contact'
  match 'users/update_emergency_contact' => 'users#update_emergency_contact'
  match 'users/delete_emergency_contact' => 'users#delete_emergency_contact'
  match 'users/add_race' => 'users#add_race'
  match 'users/add_residence_id' => 'users#add_residence_id'
  match 'users/add_form_emergency_contact' => 'users#add_form_emergency_contact'
  match '*path'  => 'home#error'

end

app/models/institution.rb
class Institution < ActiveRecord::Base
  attr_accessible :city_id, :comment, :logo, :name, :postal_code, :state_id, :street, :street2,:country_id
  has_many :users

  mount_uploader :logo, InstitutionLogo
  def self.select_institution
    self.all.map { |item| [item.name,item.id]}
  end


end

app/controllers/institutions_controller.rb
class InstitutionsController < ApplicationController
  # GET /institutions
  # GET /institutions.json
  def index
    @institutions = Institution.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @institutions }
    end
  end

  # GET /institutions/1
  # GET /institutions/1.json
  def show
    @institution = Institution.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @institution }
    end
  end

  # GET /institutions/new
  # GET /institutions/new.json
  def new
    @institution = Institution.new
    @countries = Country.all
    respond_to do |format|
      format.html # new_bk.html.erb
      format.json { render json: @institution }
    end
  end

  # GET /institutions/1/edit
  def edit
    @institution = Institution.find(params[:id])
    @countries = Country.all
  end

  # POST /institutions
  # POST /institutions.json
  def create
    p_attr = params[:institution]
    p_attr[:logo] = params[:institution][:logo].first if params[:institution][:logo].class == Array
    #p_attr[:filename] = params[:institution][:logo].original_filename
    @institution = Institution.new(p_attr)

    respond_to do |format|
      if @institution.save
        format.html { redirect_to @institution, notice: 'Institution was successfully created.' }
        format.json { render json: @institution, status: :created, location: @institution }

      else
        puts @institution.errors.full_messages
        format.html { render action: "new" }
        format.json { render json: @institution.errors, status: :unprocessable_entity }
      end

    end
  end

  # PUT /institutions/1
  # PUT /institutions/1.json
  def update
    @institution = Institution.find(params[:id])

    respond_to do |format|
      if @institution.update_attributes(params[:institution])
        format.html { redirect_to @institution, notice: 'Institution was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @institution.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /institutions/1
  # DELETE /institutions/1.json
  def destroy
    @institution = Institution.find(params[:id])
    @institution.destroy

    respond_to do |format|
      format.html { redirect_to institutions_url }
      format.json { head :no_content }
    end
  end

  def delete_institution
    Institution.destroy_all(["id IN (?)", params['list']])
    @institutions = Institution.all
    render json: :ok
  end

  def city_autocomplete

    country_id = params[:country_id]
    if (country_id.blank?)
      render json: {:data => nil}
      return
    end
    content = params[:term].downcase
    cities = City.where('lower(name) like ? AND country_id = ?', '%' + content + '%', country_id).limit(50)
    cities.collect! {|item| {:label => item.name, :id => item.id}}
    render json: {:data => cities}
  end


end

app/helpers/institutions_helper.rb
module InstitutionsHelper
end

app/views/institutions/_form.html.erb
<script type="text/javascript">
    function readURL(input) {
        var el = $('.show_logo')
        el.html('')
        $('#preview_image').show()

        if (input.files && input.files[0]) {
            var reader = new FileReader();
            reader.onload = function (e) {
                $('#preview_logo').attr('src', e.target.result);
            }
            reader.readAsDataURL(input.files[0]);
        }
    }
</script>

<div style="width: 400px;" >
<%= form_for @institution,:html => { :class => 'form_institution', :id=>"institution_new",:multipart => true  } do |f| %>


  <div class="form-inputs">
    <%= f.label :name %>
    <%= f.text_field :name %>
    <%= f.label :logo %>
    <div class="show_logo">
      <img title="" src="<%= @institution.logo %>" style="width: 70px;height: 70px;">
    </div>
    <div id="preview_image" class="hide" style="width: 150px;">
      <img id="preview_logo" src="#" style="width: 80px; height: 80px;  margin-left: 40px;"/>
    </div>
    <input type='file' name="institution[logo]" onchange="readURL(this);" />
    <%= f.label :street %>
    <%= f.text_field :street %>
    <%= f.label :street2 %>
    <%= f.text_field :street2 %>
    <%= f.label :country %>
    <%= select_tag 'country_id', options_for_select(Country.select_countries, :selected => Country.find_by_name("United States").id ), :class => "chzn-select", :name=> "institution[country_id]" %>
    <div class="control-group string optional">
      <label class="string optional control-label" for="institution_street2">City</label>
      <div class="controls">
        <input id="city_id"  type="hidden" name = "institution[city_id]"/>
        <input id="city_autocomplete" class="city-id autocomplete" autocomplete="off" type="text" />
      </div>
    </div>
    <%= f.label :state_id %>
    <%= f.text_field :state_id %>
    <%= f.label :postal_code %>
    <%= f.text_field :postal_code %>
    <%= f.label :comment %>
    <%= f.text_area :comment, :size => "60x12" %>
  </div>


  <div class="form-actions">
    <%= f.submit  %>
  </div>

<% end %>

</div>

app/views/institutions/edit.html.erb
<h1>Editing institution</h1>

<%= render 'form' %>

<%= link_to 'Show', @institution %> |
<%= link_to 'Back', institutions_path %>

app/views/institutions/index.html.erb
<h1>Listing institutions</h1>
<div class="div-head">
  <a href="/institutions/new"><button class="stdbtn" style="opacity: 1;">New</button></a>
  <a href="#" id="btn-delete"><button class="stdbtn" style="opacity: 1;">Delete</button></a>
</div>
<div class="table-content">
  <table id="list_institution" class="stdtable table-list-content">
    <thead>
    <tr>
      <th><span class="checkbox"> <input class="checkall" type="checkbox"/></span></th>
      <th>Name</th>
      <th>Logo</th>
      <th>Street</th>
      <th>Street2</th>
      <th>Country</th>
      <th>City</th>
      <th>State</th>
      <th>Postal code</th>
      <th>Comment</th>
      <th></th>
    </tr>
    </thead>

    <tbody>
    <% @institutions.each do |institution| %>
        <tr id="institution_<%=institution.id %>" >
          <td><span class="checkbox"><input  type="checkbox"/></span></td>
          <td><%= link_to institution.name, edit_institution_path(institution) %></td>
          <td><img src="<%= institution.logo %>" style="width: 70px;height: 70px;"></td>
          <td><%= institution.street %></td>
          <td><%= institution.street2 %></td>
          <td><%= institution.country_id %></td>
          <td><%= institution.city_id %></td>
          <td><%= institution.state_id %></td>
          <td><%= institution.postal_code %></td>
          <td><%= institution.comment %></td>
          <td><%= link_to 'Show', institution %></td>
        </tr>
    <% end %>
    </tbody>
  </table>
</div>
<br/>

app/views/institutions/new.html.erb
<h1>New institution</h1>

<%= render 'form' %>

<%= link_to 'Back', institutions_path %>

app/views/institutions/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Name:</b>
  <%= @institution.name %>
</p>

<p>
  <b>Logo:</b>
    <img title="" src="<%= @institution.logo %>" style="width: 70px;height: 70px;">
</p>

<p>
  <b>Street:</b>
  <%= @institution.street %>
</p>

<p>
  <b>Street2:</b>
  <%= @institution.street2 %>
</p>
<p>
  <b>Country:</b>
  <%= @institution.country_id %>
</p>
<p>
  <b>City:</b>
  <%= @institution.city_id %>
</p>

<p>
  <b>State:</b>
  <%= @institution.state_id %>
</p>

<p>
  <b>Postal code:</b>
  <%= @institution.postal_code %>
</p>

<p>
  <b>Comment:</b>
  <%= @institution.comment %>
</p>


<%= link_to 'Edit', edit_institution_path(@institution) %> |
<%= link_to 'Back', institutions_path %>