config/routes.rb
Cfa::Application.routes.draw do

  resources :uploaders do
    match '/uploaders' => 'uploaders#index'

  end

  resources :gradings  do
    collection do
      post '/answers'
      get '/add_grade_system'
      get '/add_point_grading_detail'
      get '/add_point_grading'
    end
  end

  resources :rooms

  resources :school_grades
  resources :assignment_libraries  do
    collection do
      get 'question_search'
      get 'destroy_question'
      get 'add_question'
    end
  end
  resources :school_classes do
    collection do
      get 'student_search'
      put 'add_student'
      put 'remove_student'
    end
  end

  resources :hall_of_fames
  
  resources :sponsors  do

  end
  resources :comments
  resources :relationship_types

  resources :questions

  resources :institutions do
    collection do
      post  'delete_institution'
      get 'city_autocomplete'
    end
  end


  resources :menu_items

  resources :game_assets

  resources :grade_systems

  resources :hobbies

  resources :elements

  resources :concepts

  resources :subjects

  resources :healths

  resources :residences

  resources :assignments do
    collection do
      get 'student_search'
    end
  end

  match '/educations/change_emergency_contacts'  => "educations#change_emergency_contacts"
  match '/users/change_healths' => "users#change_healths"
  resources :educations

  resources :eductations

  resources :races

  resources :phonetypes

  resources :phones

  resources :emails

  resources :states

  resources :cities

  resources :addresses

  resources :links

  resources :badges



  resources :contents do
    collection do
      match '/load_images/:id' => "contents#load_images"
      get  "search_content"
      match '/tags'  => "contents#tag"
      get 'load_tags'
      match '/edit_tag_name' => 'contents#edit_tag_name'
      match '/remove_tag/:tag_id' => 'contents#remove_tag'

    end

  end
  resources :content_photos do
    collection do
      post 'make_default'
      post 'search/:file_name' => "content_photos#search"
      post 'load_image' => "content_photos#load_image"
    end
  end
  resources :pictures
  resources :galleries do
    resources :pictures do
      collection do
        post 'make_default'
      end
    end
  end

  authenticated :user do
    root :to => 'home#index'
  end
  root :to => "home#index"
  devise_for :users,:controllers => { :registrations => "registrations",:sessions => "sessions",:passwords => "passwords",:invitations => "invitations" }

  devise_scope :user do
    match 'users/create_parent' => 'invitations#create_parent'
    match '/advanced_invitation' => 'users#advanced_invitation'

  end
  resources :users do
    resources :additional_emergency_contacts
    collection do
      post 'create_advanced_invitation'
    end

  end

  get  '/chatroom' => 'chats#room', :as => :chat
  get '/home/city_autocomplete'
  post '/new_message' => 'chats#new_message', :as => :new_message
  match '/user/update' => "users#update_user"
  match 'users/add_emergency_contact' => 'users#add_emergency_contact'
  match 'users/update_emergency_contact' => 'users#update_emergency_contact'
  match 'users/delete_emergency_contact' => 'users#delete_emergency_contact'
  match 'users/add_race' => 'users#add_race'
  match 'users/add_residence_id' => 'users#add_residence_id'
  match 'users/add_form_emergency_contact' => 'users#add_form_emergency_contact'
  match '*path'  => 'home#error'

end

app/models/content.rb
require "nokogiri"
class Content < ActiveRecord::Base
  include Tire::Model::Search
  include Tire::Model::Callbacks
  attr_accessible  :id, :name, :body, :user_id, :draft, :created_at, :updated_at, :parent_id,:tag_list

  validates :name, :presence => true, :uniqueness => true
  acts_as_taggable
  has_many :sub_contents, :class_name => "Content",
           :foreign_key => "parent_id"
  belongs_to :parent, :class_name => "Content"

  belongs_to :user
  def self.content_parents
    self.where(:parent_id => nil).map{ |item| [item.name, item.id] }
  end

  def self.fix_images
    self.all.each do |content|
      doc = Nokogiri::HTML.fragment(content.body)
      doc.css('img').each do |image|
        @query = image['src'].split('/').last
        puts @query
        image['src'] = ContentPhoto.find_by_image(@query).image.url
        content.body = doc.to_html
        if content.save
          puts content.id
        end

      end
    end
  end
  def self.fix_image_azure
    number = 0
    self.all.each do |content|
      content.update_attribute('body', content.body.gsub('https://cfa-contents.s3.amazonaws.com/images/', 'http://cfa.blob.core.windows.net/cfa/contents/'))
      number = number + 1
    end
    puts number
  end
  def self.update_body
    @contents = Content.all
    @contents.each do |content|
      content.update_attribute("body", content.body)
    end
  end

  scope :by_date, order("created_at DESC")

end

app/controllers/contents_controller.rb
require "nokogiri"
class ContentsController < ApplicationController
  # GET /contents
  # GET /contents.json
  before_filter :authenticate_user!
  def index
    if params[:query].present?
      @contents = Content.search params
    else
      if params[:tag].present?
        @contents = Content.tagged_with(params[:tag])
      else
        @contents = current_user.contents
      end
    end
    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @contents }
    end

  end

  # GET /contents/1
  # GET /contents/1.json
  def show
    @content = Content.find(params[:id])
    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @content }
    end
  end

  # GET /contents/new
  # GET /contents/new.json
  def new
    @content = Content.new
    authorize! :new, @content, :message => 'Not authorized as a teacher.'
    @pictures = ContentPhoto.paginate(:per_page => 10, :page => params[:page])
    respond_to do |format|
      format.html # new_bk.html.erb
      format.json { render json: @content }
      format.js  # new_bk.js.erb
    end
  end

  # GET /contents/1/edit
  def edit
    @content = Content.find(params[:id])
    authorize! :edit, @content, :message => 'Not authorized as a teacher.'
    @files = Dir.glob("app/assets/images/content/*")
    @directories = []
    @files.each do |file|
      @directories << File.basename(file)
    end
  end

  # POST /contents
  # POST /contents.json
  def create
    @content = Content.new(params[:content])
    authorize! :create, @content, :message => 'Not authorized as a teacher.'
    #doc = Nokogiri::HTML.fragment(params[:content][:body])
    #doc.css('img').each do |image|
    #  #Sputs image['src']
    #  @query = image['src'].split('/').last
    #  puts @query
    #  image['src'] = ContentPhoto.find_by_image(@query).image.url
    #end

    @content.user_id = current_user.id if current_user
    @content.tag_list = JSON.parse params[:content][:tag_list]
    respond_to do |format|
      if @content.save
        format.html { redirect_to @content, notice: 'Content was successfully created.' }
        format.json { render json: @content, status: :created, location: @content }
      else
        @pictures = ContentPhoto.paginate(:per_page => 10, :page => params[:page])
        format.html { render action: "new",:object => @pictures }
        format.json { render json: @content.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /contents/1
  # PUT /contents/1.json
  def update
    authorize! :update, @content, :message => 'Not authorized as a teacher.'
    @content = Content.find(params[:id])
    @content.name = params[:content][:name]
    @content.body = params[:content][:body]
    @content.draft = params[:content][:draft]
    @content.tag_list = JSON.parse params[:content][:tag_list]
    puts params[:content][:tag_list]
    respond_to do |format|
      if @content.save
        format.html { redirect_to @content, notice: 'Content was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @content.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /contents/1
  # DELETE /contents/1.json
  def destroy
    authorize! :destroy, @content, :message => 'Not authorized as a teacher.'
    @content = Content.find(params[:id])
    @content.destroy

    respond_to do |format|
      format.html { redirect_to contents_url }
      format.json { head :no_content }
    end
  end

  def tag
    @content_tags = Content.tag_counts_on(:tags)
    @contents = Content.tagged_with(params[:tag])
    respond_to do |format|
      format.html
      format.json { head :no_content }
    end
  end
  def load_tags
    @content = Content.find(params[:id])
    @content_tags = @content.tag_list

    respond_to do |format|
      format.html
      format.json {render json: @content_tags }
    end
  end
  def remove_tag
    @content_tags = Content.tag_counts_on(:tags)
    @content_tags.find(params[:tag_id]).destroy
    redirect_to '/contents/tags'
  end
  def edit_tag_name
    @content_tags = Content.tag_counts_on(:tags)
    @tag_edit = @content_tags.find(params[:tag_id])
    @tag_edit.name = params[:tag_name_edit]
    if @tag_edit.save
      render json: @tag_edit
    end
  end

  def search_content
    if params[:query].present?
      @contents = Content.search(params[:query],load: true)
    else
      @contents = Content.search(params)
    end
    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @contents }
    end
  end


end

app/helpers/contents_helper.rb
module ContentsHelper
end

app/views/contents/_form.html.erb
 </br>
<%= simple_form_for(@content,:html=> {}) do |f| %>
    <%= f.error_notification %>
    <script language="javascript" type="text/javascript">
        tinyMCE.init({
        });
         function load_tag(){
             $.ajax({
                 type: "GET",
                 url: "/contents/load_tags",
                 dataType: "json",
                 data:{ id: $("#content_id").val()},
                 success: function(data){
                     $.each(data, function (index, value) {
                     $('#textarea').textext()[0].tags().addTags([ value ]);
                    })
                 }
             });
         }
         window.onload= load_tag ;
     </script>

    <div class="form-inputs">
      <% if params[:action] == "edit" %>
        <input id="content_id" type="hidden" value=" <%= @content.id %>">
      <%end%>
      <div class="controls" style="margin-bottom: 10px;">
        <textarea id="textarea" class="example" rows="1" name="content[tag_list]" style="width: 220px;"> </textarea>
      </div>
      <div class="controls">
        <input type="text" id="tagname" placeholder="tag name" />
        <button id="addtag" class="btn" style="vertical-align: top;">Add Tag</button>
      </div>


      <label>Parent</label>
      <%= select_tag "content[parent_id]",options_for_select(Content.content_parents),:include_blank => true %>
      <%= f.input :name %>
      <label>Body</label>
      <%= text_area_tag "content[body]",@content.body,:class => "tinymce", :rows => 40, :cols => 120 ,:style => "width: 100%" %>

      <%= check_box_tag 'content[draft]',1, @content.draft %>
    </div>
    <%= tinymce %>
    <div class="form-actions">
      <%= f.button :submit %>
    </div>
<% end %>
<script type="text/javascript">
    $('#textarea').textext({ plugins: 'tags' });

    $('#addtag').bind('click', function(e)
    {
        $('#textarea').textext()[0].tags().addTags([ $('#tagname').val() ]);
        $('#tagname').val('');
        e.preventDefault();
    });
</script>

<div class="clearfix"></div>

app/views/contents/_photos.html.erb
<ul class="thumbnails files" style="margin-bottom: 80px;">
  <% unless @pictures.empty? %>
      <% @pictures.each do |pic| %>
          <li class="span3" id="picture_<%= pic.id %>">
            <div class="thumbnail">
              <a href="<%= pic.image.url %>" rel="lightbox-pictures" title="<%= pic.description.blank? ? nil : pic.description  %>">
                <img src="<%= pic.image.url %>" alt="" >
              </a>
              <div class="caption">
                <p style="text-align: center;">
                  <a href="/content_photos/<%= pic.id %>/edit" class="btn btn-mini">
                    <i class="icon-edit "></i>
                    Edit
                  </a>
                  <a class="btn btn-mini btn-delete" confirm="Are you delete ?" data-method="delete" href="/content_photos/<%= pic.id %>" data-remote=true>
                    <i class="icon-trash"></i>
                    Delete
                  </a>
                </p>
              </div>
            </div>
          </li>
      <% end %>
  <% end %>
  </ul>
<%= will_paginate @pictures %>

app/views/contents/edit.html.erb
<h1>Editing content</h1>

<%= render 'form' %>

<%= link_to 'Show', @content %> |
<%= link_to 'Back', contents_path %>

app/views/contents/index.html.erb
<h1>Content</h1>

<form method="get" id="searchform" action="#" class="form-search">
  <input type="text"  id="key_tag_search"/>
  <button type="button" id="search_content" class="btn"> Search</button>
</form>
<% Content.tag_counts_on(:tags).order(:name).each do |tag| %>
    <%= link_to tag.name, '?tag='+ tag.name,:class => 'btn' %>
<% end %>
<div id="content-list">
<table>
  <tr>
    <th style="width: 85%; text-align: left;">Name</th>
    <th style="width: 5%; text-align: center;">Draft</th>
    <th style="width: 5%; text-align: center;"></th>
    <th style="width: 5%; text-align: center;"></th>
    <th></th>
  </tr>

  <% @contents.each do |content| %>
      <tr>
        <td><%= content.name %></td>
        <td style="text-align: center;"><%= check_box_tag 'content[draft]',1, content.draft %></td>
         <td><%= link_to 'Show', content %></td>
        <td><%= link_to 'Edit', edit_content_path(content) %></td>
        </tr>
    <% end %>
  </table>
</div>

<br />

<%= link_to 'New Content', new_content_path %>

app/views/contents/new.html.erb
<h1>New content</h1>
<div class="row">
  <div style="float: left; width: 60%; display:inline-block;">
    <%= render 'form' %>
  </div>
  <div style="float: left; width: 40%;display: inline-block;">
    <%= render 'photos' %>
  </div>
</div>

<%= link_to 'Back', contents_path %>

app/views/contents/new.js.erb
$(".thumbnails.files").html("<%= escape_javascript(render("photos")) %>");

app/views/contents/show.html.erb
<p id="notice"><%= notice %></p>
  <p>
    <%= @content.tag_list %>
  </p>
 <p>
  <%= @content.name %>
</p>
  <%= @content.body.html_safe %>
<p>
  <b>Draft:</b>
  <%= check_box_tag 'content[draft]',1,@content.draft %>

</p>
<%= link_to 'Edit', edit_content_path(@content) %> |
<%= link_to 'Back', contents_path %>

app/views/contents/tag.html.erb
<table>
  <tr>
    <th style="width: 85%; text-align: left;">Name Tag</th>
    <th style="width: 5%; text-align: center;"></th>
    <th style="width: 5%; text-align: center;"></th>
    <th></th>
  </tr>

  <% @content_tags.each do |tag| %>
      <tr id="row_<%=tag.id %>">
        <td><%= link_to tag.name, '?tag='+ tag.name,:class => 'btn' %></td>
        <td><a href="#modal_edit" id="edit_tag" data-toggle="modal" >Edit</a>
          <input id="tag_id" type="hidden" value="<%= tag.id %>"/>
          <input id="tag_name" type="hidden" value="<%= tag.name %>"/>
        </td>
        <td><%= link_to 'Delete', {:action => "remove_tag", :tag_id => tag.id,
                                   :controller => "contents"} %></td>


      </tr>
  <% end %>
</table>

<table>
  <tr>
    <th style="width: 85%; text-align: left;">Name</th>
    <th style="width: 5%; text-align: center;">Draft</th>
    <th style="width: 5%; text-align: center;"></th>
    <th style="width: 5%; text-align: center;"></th>
    <th></th>
  </tr>

  <% @contents.each do |content| %>
      <tr>
        <td><%= content.name %></td>
        <td style="text-align: center;"><%= check_box_tag 'content[draft]',1, content.draft %></td>
        <td><%= link_to 'Show', content %></td>
        <td><%= link_to 'Edit', edit_content_path(content) %></td>

      </tr>
  <% end %>
</table>
<div id="modal_edit" class="modal hide fade" tabindex="-1" data-focus-on="input:first" style="width: 350px;">
  <div class="modal-header">
    <button type="button" class="close" data-dismiss="modal" aria-hidden="true">×</button>
    <h3>Edit tag</h3>
  </div>
  <div class="modal-body">
    <p>Tag name</p>
    <input type="hidden" id="tag_id_edit" name="tag_id" >
    <input type="text" id="name_tag" name="name_tag">
  </div>
  <div class="modal-footer">
    <button type="button" data-dismiss="modal" class="btn">Close</button>
    <button id="Edit_button" type="button" class="btn btn-primary">Ok</button>
  </div>
</div>