config/routes.rb
Cfa::Application.routes.draw do

  resources :uploaders do
    match '/uploaders' => 'uploaders#index'

  end

  resources :gradings  do
    collection do
      post '/answers'
      get '/add_grade_system'
      get '/add_point_grading_detail'
      get '/add_point_grading'
    end
  end

  resources :rooms

  resources :school_grades
  resources :assignment_libraries  do
    collection do
      get 'question_search'
      get 'destroy_question'
      get 'add_question'
    end
  end
  resources :school_classes do
    collection do
      get 'student_search'
      put 'add_student'
      put 'remove_student'
    end
  end

  resources :hall_of_fames
  
  resources :sponsors  do

  end
  resources :comments
  resources :relationship_types

  resources :questions

  resources :institutions do
    collection do
      post  'delete_institution'
      get 'city_autocomplete'
    end
  end


  resources :menu_items

  resources :game_assets

  resources :grade_systems

  resources :hobbies

  resources :elements

  resources :concepts

  resources :subjects

  resources :healths

  resources :residences

  resources :assignments do
    collection do
      get 'student_search'
    end
  end

  match '/educations/change_emergency_contacts'  => "educations#change_emergency_contacts"
  match '/users/change_healths' => "users#change_healths"
  resources :educations

  resources :eductations

  resources :races

  resources :phonetypes

  resources :phones

  resources :emails

  resources :states

  resources :cities

  resources :addresses

  resources :links

  resources :badges



  resources :contents do
    collection do
      match '/load_images/:id' => "contents#load_images"
      get  "search_content"
      match '/tags'  => "contents#tag"
      get 'load_tags'
      match '/edit_tag_name' => 'contents#edit_tag_name'
      match '/remove_tag/:tag_id' => 'contents#remove_tag'

    end

  end
  resources :content_photos do
    collection do
      post 'make_default'
      post 'search/:file_name' => "content_photos#search"
      post 'load_image' => "content_photos#load_image"
    end
  end
  resources :pictures
  resources :galleries do
    resources :pictures do
      collection do
        post 'make_default'
      end
    end
  end

  authenticated :user do
    root :to => 'home#index'
  end
  root :to => "home#index"
  devise_for :users,:controllers => { :registrations => "registrations",:sessions => "sessions",:passwords => "passwords",:invitations => "invitations" }

  devise_scope :user do
    match 'users/create_parent' => 'invitations#create_parent'
    match '/advanced_invitation' => 'users#advanced_invitation'

  end
  resources :users do
    resources :additional_emergency_contacts
    collection do
      post 'create_advanced_invitation'
    end

  end

  get  '/chatroom' => 'chats#room', :as => :chat
  get '/home/city_autocomplete'
  post '/new_message' => 'chats#new_message', :as => :new_message
  match '/user/update' => "users#update_user"
  match 'users/add_emergency_contact' => 'users#add_emergency_contact'
  match 'users/update_emergency_contact' => 'users#update_emergency_contact'
  match 'users/delete_emergency_contact' => 'users#delete_emergency_contact'
  match 'users/add_race' => 'users#add_race'
  match 'users/add_residence_id' => 'users#add_residence_id'
  match 'users/add_form_emergency_contact' => 'users#add_form_emergency_contact'
  match '*path'  => 'home#error'

end

app/models/badge.rb
class Badge < ActiveRecord::Base
  attr_accessible :description, :image_url, :name
end

app/controllers/badges_controller.rb
class BadgesController < ApplicationController
  # GET /badges
  # GET /badges.json
  before_filter :authenticate_user!
  def index
    @badges = Badge.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @badges }
    end
  end

  # GET /badges/1
  # GET /badges/1.json
  def show
    @badge = Badge.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @badge }
    end
  end

  # GET /badges/new
  # GET /badges/new.json
  def new
    @badge = Badge.new

    respond_to do |format|
      format.html # new_bk.html.erb
      format.json { render json: @badge }
    end
  end

  # GET /badges/1/edit
  def edit
    @badge = Badge.find(params[:id])
  end

  # POST /badges
  # POST /badges.json
  def create
    @badge = Badge.new(params[:badge])

    respond_to do |format|
      if @badge.save
        format.html { redirect_to @badge, notice: 'Badge was successfully created.' }
        format.json { render json: @badge, status: :created, location: @badge }
      else
        format.html { render action: "new" }
        format.json { render json: @badge.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /badges/1
  # PUT /badges/1.json
  def update
    @badge = Badge.find(params[:id])

    respond_to do |format|
      if @badge.update_attributes(params[:badge])
        format.html { redirect_to @badge, notice: 'Badge was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @badge.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /badges/1
  # DELETE /badges/1.json
  def destroy
    @badge = Badge.find(params[:id])
    @badge.destroy

    respond_to do |format|
      format.html { redirect_to badges_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/badges_helper.rb
module BadgesHelper
end

app/views/badges/_form.html.erb
<%= simple_form_for(@badge) do |f| %>
  <%= f.error_notification %>

  <div class="form-inputs">
    <%= f.input :name %>
    <%= f.input :description %>
    <%= f.input :image_url %>
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/badges/edit.html.erb
<h1>Editing badge</h1>

<%= render 'form' %>

<%= link_to 'Show', @badge %> |
<%= link_to 'Back', badges_path %>

app/views/badges/index.html.erb
<h1>Listing badges</h1>

<table>
  <tr>
    <th>Name</th>
    <th>Description</th>
    <th>Image url</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @badges.each do |badge| %>
  <tr>
    <td><%= badge.name %></td>
    <td><%= badge.description %></td>
    <td><%= badge.image_url %></td>
    <td><%= link_to 'Show', badge %></td>
    <td><%= link_to 'Edit', edit_badge_path(badge) %></td>
    <td><%= link_to 'Destroy', badge, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Badge', new_badge_path %>

app/views/badges/new.html.erb
<h1>New badge</h1>

<%= render 'form' %>

<%= link_to 'Back', badges_path %>

app/views/badges/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Name:</b>
  <%= @badge.name %>
</p>

<p>
  <b>Description:</b>
  <%= @badge.description %>
</p>

<p>
  <b>Image url:</b>
  <%= @badge.image_url %>
</p>


<%= link_to 'Edit', edit_badge_path(@badge) %> |
<%= link_to 'Back', badges_path %>