config/routes.rb
Cfa::Application.routes.draw do

  resources :uploaders do
    match '/uploaders' => 'uploaders#index'

  end

  resources :gradings  do
    collection do
      post '/answers'
      get '/add_grade_system'
      get '/add_point_grading_detail'
      get '/add_point_grading'
    end
  end

  resources :rooms

  resources :school_grades
  resources :assignment_libraries  do
    collection do
      get 'question_search'
      get 'destroy_question'
      get 'add_question'
    end
  end
  resources :school_classes do
    collection do
      get 'student_search'
      put 'add_student'
      put 'remove_student'
    end
  end

  resources :hall_of_fames
  
  resources :sponsors  do

  end
  resources :comments
  resources :relationship_types

  resources :questions

  resources :institutions do
    collection do
      post  'delete_institution'
      get 'city_autocomplete'
    end
  end


  resources :menu_items

  resources :game_assets

  resources :grade_systems

  resources :hobbies

  resources :elements

  resources :concepts

  resources :subjects

  resources :healths

  resources :residences

  resources :assignments do
    collection do
      get 'student_search'
    end
  end

  match '/educations/change_emergency_contacts'  => "educations#change_emergency_contacts"
  match '/users/change_healths' => "users#change_healths"
  resources :educations

  resources :eductations

  resources :races

  resources :phonetypes

  resources :phones

  resources :emails

  resources :states

  resources :cities

  resources :addresses

  resources :links

  resources :badges



  resources :contents do
    collection do
      match '/load_images/:id' => "contents#load_images"
      get  "search_content"
      match '/tags'  => "contents#tag"
      get 'load_tags'
      match '/edit_tag_name' => 'contents#edit_tag_name'
      match '/remove_tag/:tag_id' => 'contents#remove_tag'

    end

  end
  resources :content_photos do
    collection do
      post 'make_default'
      post 'search/:file_name' => "content_photos#search"
      post 'load_image' => "content_photos#load_image"
    end
  end
  resources :pictures
  resources :galleries do
    resources :pictures do
      collection do
        post 'make_default'
      end
    end
  end

  authenticated :user do
    root :to => 'home#index'
  end
  root :to => "home#index"
  devise_for :users,:controllers => { :registrations => "registrations",:sessions => "sessions",:passwords => "passwords",:invitations => "invitations" }

  devise_scope :user do
    match 'users/create_parent' => 'invitations#create_parent'
    match '/advanced_invitation' => 'users#advanced_invitation'

  end
  resources :users do
    resources :additional_emergency_contacts
    collection do
      post 'create_advanced_invitation'
    end

  end

  get  '/chatroom' => 'chats#room', :as => :chat
  get '/home/city_autocomplete'
  post '/new_message' => 'chats#new_message', :as => :new_message
  match '/user/update' => "users#update_user"
  match 'users/add_emergency_contact' => 'users#add_emergency_contact'
  match 'users/update_emergency_contact' => 'users#update_emergency_contact'
  match 'users/delete_emergency_contact' => 'users#delete_emergency_contact'
  match 'users/add_race' => 'users#add_race'
  match 'users/add_residence_id' => 'users#add_residence_id'
  match 'users/add_form_emergency_contact' => 'users#add_form_emergency_contact'
  match '*path'  => 'home#error'

end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  layout 'home'
  before_filter :authenticate_user!
  def index
    @users = User.all
  end
  def error

  end
  def city_autocomplete
    @query = "#{params[:term]}%".downcase
    @cities = City.where(["lower(name) LIKE ? and country_id = ? ", @query, params[:coutry_id]]).limit(10)
    @cities.collect! {|item| {:label => item.name, :id => item.id}}
    render :json => @cities
  end
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/home/error.html.erb
<div class="content">
  <div class="container">

    <h2>Oops!!! Its 404!</h2>
    <p class="big grey">We are sorry, the page you requested cannot be found. </p>

    <hr />
    <div class="form">
      <form method="get" id="searchform" action="#" class="form-search">
        <input type="text" value="" name="s" id="s" class="input-medium"/>
        <button type="submit" class="btn">Search</button>
      </form>
    </div>

    <div class="link-list">
      <h5>Take a look around our site</h5>
      <a href="#">Home</a> <a href="#">About us</a> <a href="#">Support</a> <a href="#">Contact Us</a> <a href="#">Disclaimer</a>
    </div>

    <div class="border"></div>

    <!-- Product & links starts -->

    <div class="prod">
      <div class="row">
        <div class="span4">
          <div class="home-links">
            <div class="col-l">
              <h5>Downloads</h5>
              <ul>
                <li><a href="#">Linux 8</a></li>
                <li><a href="#">PlayStation</a></li>
                <li><a href="#">GTalk</a></li>
                <li><a href="#">Google Search</a></li>
                <li><a href="#">Linux Phone</a></li>
              </ul>
            </div>
            <div class="col-r">
              <h5>Support</h5>
              <ul>
                <li><a href="#">Linux Update</a></li>
                <li><a href="#">PlayStation</a></li>
                <li><a href="#">GTalk</a></li>
                <li><a href="#">Google Search</a></li>
                <li><a href="#">Linux Phone</a></li>
              </ul>
            </div>
            <div class="clearfix"></div>
          </div>
        </div>
        <div class="span8">
          <div class="home-product">
            <div class="home-prod-img" id="s1">
              <img src="/assets/img/photos/s1.jpg" />
              <img src="/assets/img/photos/s2.jpg" />
              <img src="/assets/img/photos/s3.jpg" />
            </div>
            <h3>Canonical Linux 8</h3>
            <p>Aliquam ut feugiat ante. Curabitur justo aliquam. Maecenas turpis urna, eleifend et venenatis eget, ultricies quis urna. Aliquam ut feugiat ante. Curabitur justo aliquam. Aliquam ut feugiat ante. Curabitur justo aliquam. </p>
            <div class="clearfix"></div>
          </div>
        </div>
      </div>
    </div>

    <!-- Product & links ends -->

  </div>
</div>

app/views/home/index.html.erb
<!-- Slider starts -->
<% unless current_user %>
 <iframe src="http://player.vimeo.com/video/57503529" width="600" height="400" frameborder="0" webkitAllowFullScreen mozallowfullscreen allowFullScreen></iframe>
<% end %>
<% unless current_user.nil? ? false : (current_user.has_role? :student) %>
    <p><%= t('home.text_curriculum') %></p>
    <hr />
<% end %>
<!-- Hero Unit -->


<!-- Hero Ends -->




<!-- Services starts -->

<div class="services">
  <div class="row">

    <div class="span12">
      <h3>Services</h3>
    </div>
    <% if current_user.has_role? :teacher %>
    <div class="span6">
      <div class="col-l">
        <div class="service">
          <div class="b-orange serv-block">
            <i class="icon-cloud"></i>
            <h3>Gradebook</h3>
          </div>
          <a href="<%= gradings_path %>"> Visit </a><i class="icon-arrow-right"></i>
        </div>
      </div>

      <div class="col-r">
        <div class="service">
          <div class="b-purple serv-block">
            <i class="icon-briefcase"></i>
            <h3>Question</h3>
          </div>
          <a href="/questions">Visit </a><i class="icon-arrow-right"></i>
        </div>
      </div> 
      <div class="clearfix"></div>
    </div>
    <% else %>
        <div class="span3">
          <div>
            <div class="service">
              <div class="b-orange serv-block">
                <i class="icon-cloud"></i>
                <h3>Gradebook</h3>
              </div>
              <a href="<%= gradings_path %>"> Visit </a><i class="icon-arrow-right"></i>
            </div>
          </div>

        </div>
    <% end %>
    <div class="span6">
      <div class="col-l">
        <div class="service">
          <div class="b-green serv-block">
            <i class="icon-camera"></i>
            <h3>Classes</h3>
          </div>
          <a href="/school_classes">Visit </a><i class="icon-arrow-right"></i>
        </div>
      </div>
      <div class="col-r">
        <div class="service">
          <div class="b-blue serv-block">
            <i class="icon-comment"></i>
            <h3>Chat</h3>
          </div>
          <a href="/chatroom">Visit </a><i class="icon-arrow-right"></i>
        </div>
      </div>
      <div class="clearfix"></div>
    </div>
    <div class="span6">
      <div class="col-r">
        <div class="service">
          <div class="b-orange serv-block">
            <i class="icon-envelope-alt"></i>
            <h3>Mail</h3>
          </div>
          <a href="#">Visit</a><i class="icon-arrow-right"></i>
        </div>
      </div>

      <div class="clearfix"></div>
    </div>
    <% if current_user.has_role? :teacher %>
    <div class="span6">
      <div class="col-l">
        <div class="service">
          <div class="b-orange serv-block">
            <i class="icon-cloud"></i>
            <h3>Assignments</h3>
          </div>
          <a href="<%= assignments_path %>">Visit</a><i class="icon-arrow-right"></i>
        </div>
      </div>
      <div class="col-r">
         <div class="service">
           <div class="b-purple serv-block">
             <i class="icon-briefcase"></i>
             <h3>Library</h3>
           </div>
           <a href="<%= assignment_libraries_path %>">Visit</a><i class="icon-arrow-right"></i>
         </div>
          </div>
           <div class="clearfix"></div>
      </div>
    <% end %>


  </div>
</div>

<hr />

<!-- Services Ends -->





<div class="border"></div>